name: Build
on: [push, pull_request]
env:
  CI: true

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [20]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - run: node --version
      - run: npm --version

      - name: Install NPM dependencies
        run: npm ci

      - name: Lint CSS
        run: npm run lint

      - name: Compile CSS
        run: node build-css.js

      - name: Process JS
        run: node build-js.js

      - name: Build Zip
        run: node build-zip.js
